# Generated by Django 5.2.17 on 2026-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_teacher_attendancerecord_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2008-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lga_of_origin',
            field=models.CharField(default='Abeokuta South', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='student_passports/'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='physically_challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], default='Nursery', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(default='Lagos', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(help_text='e.g. JSS 1 or SS 2', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
