# Generated by Django 5.2.17 on 2026-08-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_date_of_birth_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('Kindergarten (KG)', 'Kindergarten (KG)'), ('Nursery', 'Nursery'), ('Primary', 'Primary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(help_text='e.g. Kindergarten 1, Nursery 2, Primary 3', max_length=30),
        ),
    ]
