# Generated by Django 5.2.17 on 2026-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_student_program_alter_student_religion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='student_passports/'),
        ),
    ]
