# Generated by Django 5.2.17 on 2026-08-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_student_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Expelled', 'Expelled'), ('Graduated', 'Graduated')], default='Active', max_length=20),
        ),
    ]
