# Generated by Django 5.2.17 on 2026-08-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('Kindergarten (KG)', 'Kindergarten (KG)'), ('Nursery (NUR)', 'Nursery (NUR)'), ('Primary (PRY)', 'Primary (PRY)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=30),
        ),
    ]
