# Generated by Django 5.2.17 on 2026-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_student_program_alter_student_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Transferred', 'Transferred'), ('Expelled', 'Expelled'), ('Graduated', 'Graduated')], default='Student', max_length=20),
        ),
    ]
