# Generated by Django 5.2.17 on 2026-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='passport',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='teacher_passports/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
