# Generated by Django 5.2.17 on 2026-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_teacher_date_joined_teacher_other_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birth_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='08038728754', max_length=20),
            preserve_default=False,
        ),
    ]
