# Generated by Django 5.2.17 on 2026-08-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_teacher_birth_day_teacher_birth_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
