# Generated by Django 5.2.17 on 2026-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
