# Generated by Django 5.2.17 on 2026-08-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_subject_remove_student_student_class_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150)),
                ('qualification', models.CharField(choices=[('Below SSCE', 'Below SSCE'), ('SSCE/WASSCE', 'SSCE/WASSCE'), ('OND/Diploma', 'OND/Diploma'), ('NCE', 'NCE'), ('HND', 'HND'), ('BSc', 'BSc'), ('MSc', 'MSc'), ('BA', 'BA'), ('MA', 'MA'), ('MEd', 'MEd'), ('PhD', 'PhD')], max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('is_highest', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='portal.teacher')),
            ],
            options={
                'ordering': ['-is_highest', '-year', 'id'],
            },
        ),
    ]
