# Generated by Django 5.2.17 on 2026-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_rename_is_current_academicsession_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
