# Generated by Django 5.2.17 on 2026-08-21 00:53

from django.db import migrations, models


def split_legacy_parent_names(apps, schema_editor):
    Parent = apps.get_model('portal', 'Parent')
    for parent in Parent.objects.all():
        parts = parent.name.split()
        if parts:
            parent.first_name = parts[0]
            parent.last_name = parts[-1] if len(parts) > 1 else parts[0]
            parent.middle_name = ' '.join(parts[1:-1])
            parent.save(update_fields=['first_name', 'last_name', 'middle_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_parent_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(split_legacy_parent_names, migrations.RunPython.noop),
    ]
