# Generated by Django 5.2.17 on 2026-08-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_parent_first_name_parent_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
    ]
