# Generated by Django 5.2.17 on 2026-08-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_parent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
