# Generated by Django 5.2.17 on 2026-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_parent_user_student_user_teacher_user_accountprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='broadsheet_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='reports_published',
            field=models.BooleanField(default=False),
        ),
    ]
