# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_academicterm_broadsheet_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.CreateModel(
            name='StudentExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('responses', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='portal.cbtexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='portal.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentexamsession',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam_session'),
        ),
    ]
