# Generated by Django 5.2.17 on 2026-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_cbtexam_duration_studentexamsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsession',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
