# Generated by Django 5.2.17 on 2026-08-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_studentexamsession_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
