# Generated by Django 5.2.17 on 2026-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_studentevaluation_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedCommentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('char_poor', models.TextField(help_text='Comment for character/skills average 0-2')),
                ('char_good', models.TextField(help_text='Comment for character/skills average 3-4')),
                ('char_excellent', models.TextField(help_text='Comment for character/skills average 5')),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
    ]
