# Generated by Django 5.2.17 on 2026-08-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_automatedcommentbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_statuses', to='portal.classroom')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_statuses', to='portal.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'term'), name='unique_classroom_term_result_status')],
            },
        ),
    ]
