# Generated by Django 5.2.17 on 2026-08-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_classresultstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
    ]
