# Generated by Django 5.2.17 on 2026-08-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_academicterm_next_term_begins'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_one_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('term_two_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('term_three_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cumulative_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('promotion_status', models.CharField(choices=[('Promoted', 'Promoted'), ('Repeated', 'Repeated')], default='Repeated', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_records', to='portal.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='portal.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'term'), name='unique_student_term_record')],
            },
        ),
    ]
