# Generated by Django 5.2.17 on 2026-08-27 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_studenttermrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='portal.classroom'),
        ),
    ]
