# Generated by Django 5.2.17 on 2026-08-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_classroom_next_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Student', 'Student'), ('Transferred', 'Transferred'), ('Expelled', 'Expelled'), ('Graduated', 'Graduated')], default='Student', max_length=20),
        ),
    ]
