# Generated by Django 5.2.17 on 2026-08-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_classroom_is_terminal_classroom_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_required', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='portal.classroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='portal.academicsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='portal.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'term', 'session'), name='unique_classroom_term_session_fee_structure')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_cleared', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_accounts', to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='portal.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_accounts', to='portal.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'term', 'session'), name='unique_student_term_session_fee_account')],
            },
        ),
    ]
