# Generated by Django 5.2.17 on 2026-08-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_feestructure_studentfeeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('bursar', 'Bursar')], max_length=20),
        ),
    ]
