# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='rollover_completed',
            field=models.BooleanField(default=False),
        ),
    ]