# Generated by Django 5.2.17 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_academicsession_rollover_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRolloverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(max_length=20)),
                ('created_enrollment', models.BooleanField(default=False)),
                ('closing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_records', to='portal.academicsession')),
                ('original_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollover_records', to='portal.student')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portal.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('closing_session', 'student'), name='unique_session_rollover_student')],
            },
        ),
    ]