# Generated by Django 5.2.17 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_sessionrolloverrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrolloverrecord',
            name='previous_enrollment_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.classroom'),
        ),
    ]