# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_sessionrolloverrecord_previous_enrollment_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='account_profiles/'),
        ),
    ]