# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_accountprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermrecord',
            name='promotion_notice_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]