# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_studenttermrecord_promotion_notice_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_lin_visible',
            field=models.BooleanField(default=False),
        ),
    ]