# Generated by Django 5.2.17 on 2026-08-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_student_is_lin_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded')], max_length=40)),
                ('target_description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-pk'],
            },
        ),
    ]
