# Generated by Django 5.2.17 on 2026-08-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_attendancerecord_classroom_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('bursar', 'Bursar'), ('registrar', 'Registrar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('TRUANCY_FLAGGED', 'Truancy flag raised')], max_length=40),
        ),
    ]
