# Generated by Django 5.2.17 on 2026-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_alter_accountprofile_role_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('bursar', 'Bursar'), ('teacher', 'Teacher'), ('registrar', 'Registrar'), ('parent', 'Parent'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('TRUANCY_FLAGGED', 'Truancy flag raised'), ('ROLE_CHANGED', 'User role changed')], max_length=40),
        ),
    ]
