# Generated by Django 5.2.17 on 2026-09-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_alter_accountprofile_role_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_campaigns', to='portal.academicsession')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_campaigns', to='portal.academicterm')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_reg_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('admission_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='portal.admissioncampaign')),
                ('enrolled_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_record', to='portal.student')),
                ('intended_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='portal.classroom')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
