# Generated by Django 5.2.17 on 2026-09-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_payrollrun_staffsalaryprofile_payslip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('TRUANCY_FLAGGED', 'Truancy flag raised'), ('ROLE_CHANGED', 'User role changed'), ('PAYROLL_PROCESSED', 'Payroll processed'), ('PAYROLL_APPROVED', 'Payroll approved'), ('PAYROLL_DISBURSED', 'Payroll disbursed')], max_length=40),
        ),
    ]
