# Generated by Django 5.2.17 on 2026-09-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0052_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
