# Generated by Django 5.2.17 on 2026-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_alter_payrollrun_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='disability_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='lga',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='applicant',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='passport',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='applicant_passports/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='present_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='applicant',
            name='programme_of_study',
            field=models.CharField(blank=True, choices=[('Kindergarten (KG)', 'Kindergarten (KG)'), ('Nursery (NUR)', 'Nursery (NUR)'), ('Primary (PRY)', 'Primary (PRY)')], max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_type',
            field=models.CharField(blank=True, choices=[('None', 'First School (No Previous School)'), ('Public', 'Public'), ('Private', 'Private')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
