# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models


def create_default_payment_account(apps, schema_editor):
    SchoolPaymentAccount = apps.get_model('portal', 'SchoolPaymentAccount')
    SchoolPaymentAccount.objects.get_or_create(
        account_number='1223688239',
        defaults={
            'bank_name': 'Zenith Bank',
            'account_name': 'Future Leaders Private Academy',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_applicant_disability_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'bank_name', 'account_name'],
            },
        ),
        migrations.RunPython(create_default_payment_account, migrations.RunPython.noop),
    ]