# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models


def migrate_campaign_statuses(apps, schema_editor):
    AdmissionCampaign = apps.get_model('portal', 'AdmissionCampaign')
    AdmissionCampaign.objects.filter(is_active=True).update(status='Active')
    AdmissionCampaign.objects.filter(is_active=False).update(status='Closed')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_schoolpaymentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncampaign',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Active', max_length=10),
        ),
        migrations.RunPython(migrate_campaign_statuses, migrations.RunPython.noop),
    ]