# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_admissioncampaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='provisioned_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_parent_record', to='portal.parent'),
        ),
    ]