# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_applicant_provisioned_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='generated_parent_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='applicant',
            name='generated_student_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]