# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_applicant_generated_directory_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='generated_student_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='generated_parent_id',
            new_name='parent_id',
        ),
    ]