# Generated by Django 5.2.17 on 2026-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0059_rename_applicant_directory_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='admission_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
