# Generated by Django 5.2.17 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0065_alter_applicant_last_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='school_type',
            field=models.CharField(blank=True, choices=[('None', 'First School (No Previous School)'), ('Public', 'Public'), ('Private', 'Private')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='temp_reg_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
