# Generated by Django 5.2.17 on 2026-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('portal', '0066_alter_applicant_school_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='term_name',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=100),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('bursar', 'Bursar'), ('teacher', 'Teacher'), ('registrar', 'Registrar'), ('parent', 'Parent'), ('student', 'Student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='admission_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='father_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='student_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('TRUANCY_FLAGGED', 'Truancy flag raised'), ('ROLE_CHANGED', 'User role changed'), ('PAYROLL_PROCESSED', 'Payroll processed'), ('PAYROLL_APPROVED', 'Payroll approved'), ('PAYROLL_DISBURSED', 'Payroll disbursed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cbtattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cbtresponse',
            name='answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(choices=[('KG', 'Kindergarten'), ('Nursery', 'Nursery'), ('Primary', 'Primary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Important', 'Important'), ('Urgent', 'Urgent')], default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed')], default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolpaymentaccount',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionrolloverrecord',
            name='original_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffsalaryprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Student', 'Student'), ('Transferred', 'Transferred'), ('Expelled', 'Expelled'), ('Graduated', 'Graduated')], default='Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studenttermrecord',
            name='promotion_status',
            field=models.CharField(choices=[('Promoted', 'Promoted'), ('Repeated', 'Repeated')], default='Repeated', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherqualification',
            name='qualification',
            field=models.CharField(choices=[('Below SSCE', 'Below SSCE'), ('SSCE/WASSCE', 'SSCE/WASSCE'), ('OND/Diploma', 'OND/Diploma'), ('NCE', 'NCE'), ('HND', 'HND'), ('BSc', 'BSc'), ('MSc', 'MSc'), ('BA', 'BA'), ('MA', 'MA'), ('MEd', 'MEd'), ('PhD', 'PhD')], max_length=100),
        ),
    ]
