# Generated by Django 5.2.17 on 2026-09-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_add_push_subscription_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='portal.classroom')),
            ],
            options={
                'ordering': ['target_class__section', 'target_class__sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='portal.classroom')),
            ],
            options={
                'ordering': ['target_class__section', 'target_class__sequence', 'is_optional', 'id'],
            },
        ),
    ]
