# Generated by Django 5.2.17 on 2026-09-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0071_bookitem_feeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeItem',
        ),
    ]
