# Generated by Django 5.2.17 on 2026-09-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_populate_kg1_nursery2_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.feestructure')),
            ],
            options={
                'ordering': ['-is_compulsory', 'id'],
            },
        ),
    ]
