# Generated by Django 5.2.17 on 2026-09-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0076_migrate_amount_required_to_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='amount_required',
        ),
    ]
