# Generated by Django 5.2.17 on 2026-09-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0077_remove_fee_structure_amount_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='portal.student'),
        ),
        migrations.AlterField(
            model_name='studentfeeaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='portal.student'),
        ),
        migrations.AlterField(
            model_name='termenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrollments', to='portal.student'),
        ),
    ]
