# Generated by Django 5.2.17 on 2026-09-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0078_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portal.feestructureitem'),
        ),
    ]
