# Generated by Django 5.2.17 on 2026-09-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0079_feepayment_fee_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='portal.parent'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent_profile_is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
