# Generated by Django 5.2.17 on 2026-10-01 22:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0082_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('BROADSHEET_APPROVED', 'Broadsheet approved'), ('BROADSHEET_DISAPPROVED', 'Broadsheet disapproved'), ('RESULT_PUBLISHED', 'Results published'), ('RESULT_UNPUBLISHED', 'Results unpublished'), ('SCORE_MODIFIED', 'Scores modified'), ('COMMENT_MODIFIED', 'Comment modified'), ('DEBT_OVERRIDDEN', 'Debt clearance changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('INVOICES_GENERATED', 'Class invoices generated'), ('TRUANCY_FLAGGED', 'Truancy flag raised'), ('ROLE_CHANGED', 'User role changed'), ('PAYROLL_PROCESSED', 'Payroll processed'), ('PAYROLL_APPROVED', 'Payroll approved'), ('PAYROLL_DISBURSED', 'Payroll disbursed'), ('PARENT_BALANCE_CREDITED', 'Parent school payment balance credited'), ('PARENT_BALANCE_DEBITED', 'Parent school payment balance debited'), ('RESULT_ACCESS_PAID', 'Result access fee paid')], max_length=100),
        ),
        migrations.CreateModel(
            name='ParentPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='portal.parent')),
            ],
            options={
                'ordering': ['parent__name'],
            },
        ),
        migrations.CreateModel(
            name='ParentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('source', models.CharField(choices=[('PAYSTACK_DVA', 'Paystack Dedicated Virtual Account'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment / Test Credit'), ('CHARGE_PAYMENT', 'Applied to a school charge'), ('REVERSAL', 'Reversal / Adjustment')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Reversed', 'Reversed'), ('Failed', 'Failed')], default='Successful', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_ledger_entries', to='portal.student')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='portal.parentpaymentaccount')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResultAccessFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_access_fees', to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_access_fees', to='portal.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_access_fees', to='portal.academicterm')),
            ],
            options={
                'ordering': ['-session__name', 'term__start_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'term', 'session'), name='unique_student_term_session_result_access_fee')],
            },
        ),
    ]
