# Generated by Django 5.2.17 on 2026-10-03 21:06

from django.conf import settings
from django.db import migrations, models


def seed_bank_accounts(apps, schema_editor):
    # Same details previously hardcoded in the parent payment channels.
    SchoolBankAccount = apps.get_model('portal', 'SchoolBankAccount')
    if SchoolBankAccount.objects.exists():
        return
    SchoolBankAccount.objects.create(category='School Fees', bank_name='Zenith Bank', account_number='1223688239', account_name='Future Leaders Private Academy')
    SchoolBankAccount.objects.create(category='Other Payments', bank_name='Providus Bank', account_number='6507146199', account_name='Funmilayo Fasina')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0083_alter_auditlog_action_type_parentpaymentaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('School Fees', 'School Fees'), ('Other Payments', 'Other Payments')], max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', '-is_active'],
            },
        ),
        migrations.AddField(
            model_name='parentledgerentry',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='parentledgerentry',
            name='source',
            field=models.CharField(choices=[('PAYSTACK_DVA', 'Paystack Dedicated Virtual Account'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('MANUAL_BANK_TRANSFER', 'Manual Bank Transfer Credit'), ('MANUAL_CORRECTION', 'Correction'), ('CHARGE_PAYMENT', 'Applied to a school charge'), ('REVERSAL', 'Reversal / Adjustment')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='parentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('external_reference',), name='unique_ledger_external_reference'),
        ),
        migrations.RunPython(seed_bank_accounts, migrations.RunPython.noop),
    ]
