# Generated by Django 5.2.17 on 2026-10-03 22:13

from django.db import migrations, models


def christmas_contact_school(apps, schema_editor):
    # Christmas has no school account yet; parents are told to contact management.
    apps.get_model('portal', 'FeeStructureItem').objects.filter(description__icontains='christmas').update(payment_account='Contact School')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0084_school_bank_accounts_manual_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructureitem',
            name='payment_account',
            field=models.CharField(choices=[('Other Payments', 'Other Payments account'), ('School Fees', 'School Fees account'), ('Contact School', 'Contact school management')], default='Other Payments', max_length=20),
        ),
        migrations.RunPython(christmas_contact_school, migrations.RunPython.noop),
    ]
